# Generated by Django 4.0.4 on 2022-06-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
    ]
