# Generated by Django 4.0.4 on 2022-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.CharField(default=100, max_length=25),
            preserve_default=False,
        ),
    ]
